export const SEARCH_FOUCES ='header/SEARCH_FOCUS'
export const SEARCH_BLUE = 'header/SEARCH_BLUE'
export const  CHANGE_LIST = 'header/CHANGE_LIST'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const CHANGEPAGE ='header/CHANGEPAGE'